name: discord-bot
region: london  
workers:  
  - name: worker  
    environment_slug: python  
    github:  
      repo: jasminefederer/donna_harraway_discord_bot
      branch: main  
    instance_count: 1  
    instance_size_slug: basic-xxs 
    run_command: python bot.py 
